Task7 create user method
RailyanuArkady/userService pull request #7
Opened 2024-03-11 18:02 UTC by RexArrHub

2024-03-11 21:27 UTC, RailyanuArkady requested changes

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/java/org/user_service/controller/UserController.java
> +        return new ResponseEntity<>(response, HttpStatus.CREATED);
возвращать, ResponseEntity тут необходимости нет, это старперский вариант, настоящие Json стэтхемы используют аннотацию HTTPRESPONSE или как-то так, точно не помню погугли. Также метод должен возвращать по аналитике UID, твой метод возвращает UserResponseDto, что не соответсвует аналитике, получишь по жопе от бизнеса

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/java/org/user_service/controller/UserController.java
> +        return new ResponseEntity<>(response, HttpStatus.CREATED);
должно быть return userService.save(UserDto)

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/java/org/user_service/dto/PassportDTO.java
> +public class PassportDTO {
используем фичи java 17, вместо class используем record

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/java/org/user_service/dto/PassportDTO.java
> +    @NotNull
для String лучше использовать NotBlank он помимо null еще и на пустые строки проверяет, твой код схавает строку "    ", поэтому тут и в других подобных местах лучше использовать Pattern

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/java/org/user_service/dto/UserDTO.java
> +    @NotNull
возможно понадобится аннотация valid еще, не уверен что паспорт валидируется, но это не точно

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/java/org/user_service/dto/UserResponseDto.java
> +public class UserResponseDto {
в этом классе нет смысла

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/java/org/user_service/model/Passport.java
> +    @PrePersist
убрать, я один раз также сделал на подобной задачи, я примерно догадываюсь зачем ты решил это сделать, за идею хвалю, но тут и без преперсистов можно разрулить почитай про expression в mapstruct, аннотация Mapping, если в мапстракте решил задавать UID то убери везде аннотации UID генератор

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/java/org/user_service/model/User.java
> +    @PrePersist
убрать

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/java/org/user_service/repository/PassportRepository.java
> +@Repository
нет необходимости в данной аннотации, ее содержит класс от которого наследуешься

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/java/org/user_service/services/PassportServiceClass.java
> +public class PassportServiceClass {
PassportService - и так понятно что это класс

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/java/org/user_service/controller/RestExceptionHandler.java
> +@ControllerAdvice
RestControllerAdvice

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/java/org/user_service/controller/RestExceptionHandler.java
> +public class RestExceptionHandler extends ResponseEntityExceptionHandler {
наследоваться ненадо 
следим за неймингом твой крайне неинформативен, UserExceptionHandler

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/java/org/user_service/controller/RestExceptionHandler.java
> +        return new ResponseEntity<>(response, HttpStatus.BAD_REQUEST);
избавляемся от старпер кода, статус возвращаем аннотацией ResponseStatus(HttpStatus.BAD_REQUEST), а метод соотвественно возвращает ErrorResponseDto

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/java/org/user_service/controller/RestExceptionHandler.java
> +    protected ResponseEntity<Object> handleMethodArgumentNotValid(MethodArgumentNotValidException e,
метод не должен принимать ничего кроме ValidationException ex, зачем тебе остальные аргументы, ты же все равно их не используешь, как перестанешь наследоваться у тебя и override не надо будет делать

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/java/org/user_service/controller/RestExceptionHandler.java
> +        ValidationExceptionBody response = new ValidationExceptionBody(HttpStatus.BAD_REQUEST.value(), e.getMessage(), Instant.now());
какой иснтант. Либо LocalDateTime.now либо OffsetDateTime.now

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/java/org/user_service/controller/RestExceptionHandler.java
> +    @ExceptionHandler(DataIntegrityViolationException.class)
скорее всего можно написать просто Exception.class зачем тебе какой-то непонятный DataIntegrity первый раз его вижу, а если у тебя возникнет ошибка при парсинге Json или при сохранении в базу, такие исключение у тебя не отловятся

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/java/org/user_service/controller/UserController.java
> +    public UserController(UserServiceClass userServiceClass) {
убрать, вместо этого повесить аннотацию RequiredArgsConstructor  на класс и так сделать везде, используем активно технологии, поменьше старпер кода у тебя ломбок и 17 джава

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/java/org/user_service/dto/UserDTO.java
> +public class UserDTO {
не понял, что за Dto у нас уговор что явно называем Response и Request, смени название на UserRequestDto и разнеси реквесты и респоны в два разных пакета внутри пакета Dto. response и request соответсвенно

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/java/org/user_service/services/PassportServiceClass.java
> +    public PassportServiceClass(PassportRepository passportRepository) {
RequieredArgsConstructor

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/java/org/user_service/services/PassportServiceClass.java
> +    public void save (PassportDTO passportDTO){
жмем ctrl + alt + l и ctrl + alt + o перед ревью, нужно уважать своих коллег. почему где-то Dto а где - то DTO определись и везде поменяй

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/java/org/user_service/services/PassportServiceClass.java
> +public class PassportServiceClass {
удаляем сервис, но ошибки на которые указал, учитываем при написании других сервисов

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/java/org/user_service/services/UserServiceClass.java
> +    UserAndPassportMapper userAndPassportMapper = new UserAndPassportMapperImpl();
что за ужас, private final спринг внедрит это, никаких new

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/java/org/user_service/mapper/UserAndPassportMapper.java
> +public interface UserAndPassportMapper {
нет, меняем название на UserMapper, также нужен будет класс PassportMapper

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/java/org/user_service/mapper/UserAndPassportMapper.java
> +@Mapper
Mapper(componentModel = "spring") нужно добавить в спринг контекст

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/java/org/user_service/mapper/UserAndPassportMapper.java
> +@Mapper
так же надо будет дописать uses, ну ты сам разберешься уже дальше какой

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/java/org/user_service/mapper/UserAndPassportMapper.java
> +    @Mapping(source = "phone", target = "phone")
тут как в хибере нет смысла указывать поля которые называются одинаково, указываем явно только расхождения

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/java/org/user_service/mapper/UserAndPassportMapper.java
> +    @InheritInverseConfiguration
прикольная аннотация, не знал про нее, молодец

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/java/org/user_service/mapper/UserAndPassportMapper.java
> +    PassportDTO passportToPassportDTO(Passport passport);
в отдельный класс

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/java/org/user_service/services/UserServiceClass.java
> +    public UUID save(UserDTO userDTO){
ctrl + alt + l. На будущее сразу договоримся, лучше писать saveUser, в целом мне и так понятно что этот метод сохраняет пользователя, потому что он принимает User и находится в UserService, но лично мне больше нравятся подробные описания, как и большинство разрабов что встречал, но это чисто вкусовщина

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/java/org/user_service/services/UserServiceClass.java
> +    public UUID save(UserDTO userDTO){
метод слишком жирный, по нему сразу видно что ты не разобрался ни в хибере, ни в мапрстракте, у тебя должно быть 2 строчки кода 
1) user = маппер отдай пользователя 
2) return save(user).getExternalId

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/java/org/user_service/util/UserOrPassportValidationException.java
> +public class UserOrPassportValidationException extends MethodArgumentNotValidException {
лишний класс

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/java/org/user_service/util/ValidationExceptionBody.java
> +public class ValidationExceptionBody {
переиминовать класс, сделать рекордом

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/java/org/user_service/util/ValidationExceptionBody.java
> +    private final Instant timeStamp;
ну про время ты знаешь

2024-03-11 21:27 UTC, RailyanuArkady commented on src/main/resources/application.yaml
> +    allow-bean-definition-overriding: true
убери

2024-03-11 21:28 UTC, RailyanuArkady requested changes

2024-03-11 21:28 UTC, RailyanuArkady commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-validation:3.2.3'
какие аннотации эта зависимость дала тебе ? Тебе не нужна эта аннотация, + версию можно не писать, она у нас унифицирована для всех стартеров спринг бута

2024-03-14 19:56 UTC, RailyanuArkady requested changes

2024-03-14 19:56 UTC, RailyanuArkady commented on src/main/java/org/user_service/controller/UserController.java
> +    private final UserServiceClass userServiceClass;
UserService и так понятно что это класс. Тут не может быть ничего другого, ты же не назвал UserControlleClass в джава все классы поэтому добавлять класс окончание смысла нет

2024-03-14 19:56 UTC, RailyanuArkady commented on src/main/java/org/user_service/controller/exception_handler/UserExceptionHandler.java
> +public class UserExceptionHandler {
давай сменим название на UserServiceExceptionHandler

2024-03-14 19:56 UTC, RailyanuArkady commented on src/main/java/org/user_service/dto/request/PassportRequestDTO.java
> +        @Size(min = 4, max = 4)
min max не надо у тебя паттерн и так говорит что символов должно быть 4

2024-03-14 19:56 UTC, RailyanuArkady commented on src/main/java/org/user_service/dto/request/PassportRequestDTO.java
> +        @Valid
Валид ставим только над классами своими классами чтобы Спринг их провалидировал, над стрижкой смысла нет

2024-03-14 19:56 UTC, RailyanuArkady commented on src/main/java/org/user_service/dto/request/UserRequestDTO.java
> +        PassportRequestDTO passport) {
а вот тут может надо поставить аннотацию Валид иначе без нее паспорт не будет валидироваться но я точно не помню может и будет это мы только императивным путем можем узнать если что резовли этот коммент

2024-03-14 19:56 UTC, RailyanuArkady commented on src/main/java/org/user_service/dto/request/UserRequestDTO.java
> +        String phone,
```
public record UserRecord(@Pattern(regexp = "^\\d{11}$", message = "Неверный формат номера телефона") String phoneNumber) {
    
    public UserRecord {
        this.phoneNumber = phoneNumber.replaceAll("\\D", "");
    }
}
```
чет типо такого чтобы сразу можно было сразу получить валидный + готовый номер телефона на старте, дальше с ним намного проще будет работать соотвественно логику из мапстракта можно будет вынести + меньше времени будем находится в транзакции + такой подход работает быстрее потому что мы даже в контроллер не зайдем с говно номером

2024-03-14 19:56 UTC, RailyanuArkady commented on src/main/java/org/user_service/repository/PassportRepository.java
> +    @Query("SELECT u.id FROM User u WHERE id = ?1")
не нужно для решения твоей задачи

2024-03-14 19:56 UTC, RailyanuArkady commented on src/main/java/org/user_service/services/UserServiceClass.java
> +        Passport passport = passportMapper.passportRequestDTOToPassport(userRequestDTO.passport());
лишняя строчка, предыдущая должна уже вернуть user внутри которого есть паспорт для паспорта просто делаешь user.getPassport

2024-03-14 19:56 UTC, RailyanuArkady commented on src/main/java/org/user_service/services/UserServiceClass.java
> +        passport.setUser(user);
не нужно

2024-03-14 19:56 UTC, RailyanuArkady commented on src/main/java/org/user_service/util/ValidationExceptionBody.java
> +public record ValidationExceptionBody(int error, String description, LocalDateTime timeStamp) {
переименовать в ErrorResponseDto

2024-03-14 19:56 UTC, RailyanuArkady commented on src/main/java/org/user_service/util/ValidationExceptionBody.java
> +public record ValidationExceptionBody(int error, String description, LocalDateTime timeStamp) {
и перенести в пакет dto.response

2024-03-15 13:42 UTC, RexArrHub commented on src/main/java/org/user_service/controller/UserController.java
> +    private final UserServiceClass userServiceClass;
Просто у нас мейн класс называется UserService и я временно этот так назвал чтоб не путать

2024-03-15 17:05 UTC, RexArrHub commented on src/main/java/org/user_service/dto/request/UserRequestDTO.java
> +    public UserRequestDTO {
Т.к сначала идёт в конструктор потом смотрит на аннотации над полями, пришлось обе проверки туда и засунуть

2024-03-15 20:00 UTC, RailyanuArkady approved these changes

2024-03-15 20:14 UTC, RailyanuArkady approved these changes

2024-03-15 20:15 UTC, RailyanuArkady approved these changes
все ок

2024-03-15 20:15 UTC, merged